---
# Used together with host_vars/monitoring.ooni.org/vars.yml
modules:
  http_2xx:
    prober: http
    timeout: 30s
    http:
      preferred_ip_protocol: ip4
  http_post_2xx:
    prober: http
    timeout: 30s
    http:
      method: POST
  tcp_connect:
    prober: tcp
    timeout: 30s
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    timeout: 30s
    tcp:
      preferred_ip_protocol: ip4
      query_response:
      - expect: "^SSH-2.0-"
        send: "SSH-2.0-blackbox_exporter OONI-prometheus-0.0\x0d" # WTF: \x0a is auto-added https://github.com/prometheus/blackbox_exporter/blob/master/tcp.go#L127
      # FIXME: `blackbox_exporter` waits for newline, so we can't wait for handshake :-(
      # - expect: "diffie-hellman-group14-sha1.*ssh-dss.*hmac-sha1.*hmac-sha1.*none.*none"
  irc_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4

  tls_snakeoil:
    prober: tcp
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: true

  # When using this prober, be sure to target:
  # https://collector.ooni.io/invalidpath
  ooni_collector_ok:
    prober: http
    http:
      valid_status_codes: [404]
      method: GET

  # When using this prober, be sure to target:
  # https://bouncer.ooni.io/bouncer/net-tests
  ooni_bouncer_ok:
    prober: http
    http:
      method: POST
      headers:
        Content-Type: application/json
      body: '{"net-tests":[{"input-hashes":null,"name":"web_connectivity","test-helpers":["web-connectivity"],"version":"0.0.1"}]}'
      fail_if_body_not_matches_regexp:
      - '"web-connectivity":' # some bouncer-like response

  # When using this prober, be sure to target:
  # https://web-connectivity.th.ooni.io/status
  ooni_web_connectivity_ok:
    prober: http
    http:
      valid_status_codes: [200]
      method: GET
      fail_if_body_not_matches_regexp:
        - ".+?\"status\".+?\"ok\".+?"

  # Send JSON with a POST to a new test helper to run a real http_request and tcp_connect test
  new_test_helper_health:
    prober: http
    timeout: 25s
    http:
      valid_status_codes: [200]
      method: POST
      headers:
        Content-Type: application/json
      body: '{"http_request":"https://google.com/","http_request_headers":{},"tcp_connect":["8.8.8.8:443"]}'
      fail_if_body_not_matches_regexp:
        - "Google"

  ooni_tcp_echo_ok:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - send: "TEST"
        - expect: "TEST"

  ooni_http_return_json_headers_ok:
    prober: http
    http:
      valid_status_codes: [200]
      method: GET
      fail_if_body_not_matches_regexp:
        - ".+?\"headers_dict\".+?"

  ooni_orchestrate:
    prober: http
    http:
      fail_if_body_not_matches_regexp:
      - "\"category_code\":"

  ooni_registry:
    prober: http
    http:
      valid_status_codes: [404]
      method: GET
      fail_if_body_not_matches_regexp:
      - "404 page not found"

  https_2xx_json:
    http:
      method: GET
      valid_status_codes: []  # Defaults to 2xx
      fail_if_not_ssl: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
      headers:
        User-Agent: ooni blackbox
      no_follow_redirects: false
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_body_not_matches_regexp:
        - "}"
    prober: http
    timeout: 30s

  https_2xx_json_meta:
    http:
      method: GET
      valid_status_codes: []  # Defaults to 2xx
      fail_if_not_ssl: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
      headers:
        User-Agent: ooni blackbox
      no_follow_redirects: false
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_body_not_matches_regexp:
        - "metadata"
    prober: http
    timeout: 30s

...
