# # Vector

- name: vector - enable repo
  tags: vector
  shell: extrepo enable vector && extrepo update vector

- name: vector - install pkg
  tags: vector
  apt:
    # refresh cache
    cache_valid_time: 0
    name:
      - vector

- name: vector - deploy SQL file to create logs table
  tags: vector
  copy:
    src: create_logs_table.sql
    dest: /etc/clickhouse-server/create_logs_table.sql

- name: vector - create vector_logs table
  tags: vector
  command: clickhouse-client --multiline --multiquery --queries-file /etc/clickhouse-server/create_logs_table.sql

- name: vector - Generate syslog certificates
  tags: vector
  # runs locally
  delegate_to: 127.0.0.1
  shell: |
    ./vault view files/pusher_ca.key.vault | openssl req -x509 -new -nodes -key /dev/stdin -sha256 -days 3650 -subj '/O=OONI/OU=CA/CN=ooni.org' -out oonicacert.pem
    openssl req -newkey rsa:2048 -nodes -days 3650 -keyout node.key -out node-req.pem -subj '/CN=ooni.org/O=OONI temp CA/C=US' -batch
    ./vault view files/pusher_ca.key.vault | openssl x509 -req -days 3650 -set_serial 01 -in node-req.pem -out node-cert.pem -CA oonicacert.pem -CAkey /dev/stdin
  register: certs_ready

- name: vector - Copy TLS certs
  tags: vector
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/vector/
    mode: '0440'
    owner: vector
  loop:
    - oonicacert.pem
    - node-cert.pem
    - node.key
  when: certs_ready.changed

- name: vector - Delete files
  tags: vector
  # runs locally
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - node-cert.pem
    - node-req.pem
    - node.key
    - oonicacert.pem

- name: vector - configure
  tags: vector
  template:
    src: templates/vector.toml
    dest: /etc/vector/vector.toml

- name: vector - open port
  tags: vector
  ansible.builtin.copy:
    src: templates/10514.nft
    dest: /etc/ooni/nftables/tcp/
  register: nft_reload_needed

- name: vector - reload nft
  tags: vector
  shell: systemctl reload nftables.service
  when: nft_reload_needed.changed

- name: vector - restart service
  tags: vector
  systemd:
    daemon_reload: yes
    enabled: yes
    name: vector.service
    state: restarted
