yace_exported_tags_on_metrics:
  ecs-svc:
    - Name

yace_discovery_jobs:
  - type: AWS/ECS
    regions:
      - eu-central-1
    period: 60
    length: 300
    searchTags:
      - key: Environment
        value: dev
    dimensionNameRequirements:
      - ClusterName
      - ServiceName
    metrics:
      - name: RunningTaskCount
        statistics:
          - Average
      - name: DesiredTaskCount
        statistics:
          - Average
      - name: PendingTaskCount
        statistics:
          - Average
