- name: reload nftables
  tags: nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded

- name: restart chrony
  ansible.builtin.systemd:
    name: chrony.service
    state: restarted

- name: restart netdata
  ansible.builtin.systemd:
    name: netdata.service
    state: restarted
