- name: Install config file
  template:
    src: blackbox.yml
    dest: "/etc/prometheus/blackbox.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart blackbox_exporter
  tags:
    - monitoring
    - blackbox_exporter
    - config

- name: Setcap
  command: setcap cap_net_raw=ep /usr/bin/prometheus-blackbox-exporter
  tags:
    - monitoring
    - blackbox_exporter
    - config
  notify:
    - restart blackbox_exporter
