tasks:
  - name: install base deps
    ansible.builtin.apt:
      name:
        - "awscli"
        - "etckeeper"
        - "git"
        - "python3-dnspython"
        - "python3-boto3"
        - "tmux"
        - "vim"
      state: "latest"
      update_cache: "yes"
