---

## API ##

- name: install API if not present
  # do not update package if present
  tags: api
  apt:
    cache_valid_time: '{{ apt_cache_valid_time }}'
    name: ooni-api
    state: present
    update_cache: yes

- name: create Nginx cache dir
  file:
    path: /var/cache/nginx/ooni-api
    state: directory

- name: configure api
  tags: api
  template:
    src: api.conf
    dest: /etc/ooni/api.conf
    owner: ooniapi
    group: ooniapi
    mode: 0640
  vars:
    github_push_repo: "ooni-bot/test-lists"
    github_origin_repo: "ooni/test-lists"
    login_base_url: "https://test-lists.test.ooni.org/login"
    pg_uri: ""
    # mail_smtp_password: "DISABLED"
    # jwt_encryption_key and account_id_hashing_key are taken from the vault

- name: create Psiphon conffile
  tags: api
  copy:
    content: "{{ psiphon_config }}"
    dest: /etc/ooni/psiphon_config.json

- name: Write Tor targets conffile
  tags: api
  template:
    src: tor_targets.json
    dest: /etc/ooni/tor_targets.json

- name: configure api uploader using s3 bucket
  tags: api
  template:
    src: templates/api-uploader.conf
    dest: /etc/ooni/api-uploader.conf

## Nginx ##

- name: Overwrite API nginx conf
  tags: api, webserv
  template:
    src: templates/nginx-api.conf
    dest: /etc/nginx/sites-available/ooni-api.conf
    mode: 0755
    owner: root
  vars:
    # Uses dehydrated
    certpath: /var/lib/dehydrated/certs/

- name: Create symlink for API nginx conf
  tags: api
  file:
    src=/etc/nginx/sites-available/ooni-api.conf
    dest=/etc/nginx/sites-enabled/ooni-api.conf
    state=link

- name: Configure deb forwarder
  tags: deb_ooni
  # Uses dehydrated
  template:
    src: deb_ooni_org.nginx.conf
    dest: /etc/nginx/sites-enabled/deb_ooni
  notify:
    - reload nginx
    - restart nginx

- name: Deploy dehydrated conf
  tags: api, webserv
  template:
    src: templates/dehydrated.config
    dest: /etc/dehydrated/config
    mode: 0755
    owner: root

- name: Deploy API gunicorn conf
  tags: api
  template:
    src: api.gunicorn.py
    dest: /etc/ooni/api.gunicorn.py
    owner: ooniapi
    group: ooniapi
    mode: 0640

- name: create badges dir
  tags: api
  file:
    path: /var/www/package_badges/
    state: directory

- name: allow incoming TCP connections to API
  tags: api
  blockinfile:
    path: /etc/ooni/nftables/tcp/443.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 443 counter accept comment "incoming HTTPS"
  notify:
    - reload nftables

## Fastpath ##

- name: install fastpath if not present
  tags: fastpath
  apt:
    cache_valid_time: 86400
    name: "fastpath={{ fastpath_version }}"
    state: present

- name: configure fastpath on test
  tags: fastpath
  template:
    src: fastpath.conf
    dest: /etc/ooni/fastpath.conf
    owner: fastpath
    group: fastpath
    mode: 0640

## Analysis daemon ##

- name: install analysis
  # do not update package if present
  tags: analysis
  apt:
    cache_valid_time: 86400
    name: "analysis={{ analysis_version }}"
    force: True
    state: present

- name: configure analysis
  tags: analysis-conf
  template:
    src: analysis.conf
    dest: /etc/ooni/analysis.conf

## DB backup ##

- name: Run DB backup
  tags: dbbackup
  template:
    src: db-backup.conf
    dest: /etc/ooni/db-backup.conf
    mode: 0600
