---

## API ##

- name: install API if not present
  # do not update package if present
  tags: api
  apt:
    cache_valid_time: '{{ apt_cache_valid_time }}'
    name: ooni-api
    state: present
    update_cache: yes

- name: create Nginx cache dir
  file:
    path: /var/cache/nginx/ooni-api
    state: directory

- name: configure test api
  when: inventory_hostname == 'backend-hel.ooni.org'
  tags: api
  template:
    src: api.conf
    dest: /etc/ooni/api.conf
    owner: ooniapi
    group: ooniapi
    mode: 0640
  vars:
    collectors: ['backend-hel.ooni.org']
    # bucket_name and collector_id must match the uploader
    collector_id: 2
    bucket_name: ooni-data-eu-fra-test
    github_push_repo: "ooni-bot/test-lists"
    github_origin_repo: "ooni/test-lists"
    login_base_url: "https://test-lists.test.ooni.org/login"
    pg_uri: ""
    clickhouse_url: clickhouse://api:api@localhost/default
    # mail_smtp_password: "DISABLED"
    # jwt_encryption_key and account_id_hashing_key are taken from the vault

- name: configure backend-fsn api
  when: inventory_hostname == 'backend-fsn.ooni.org'
  tags: api
  template:
    src: api.conf
    dest: /etc/ooni/api.conf
    owner: ooniapi
    group: ooniapi
    mode: 0640
  vars:
    collectors: ['backend-fsn.ooni.org']
    # bucket_name and collector_id must match the uploader
    collector_id: 1
    bucket_name: ooni-data-eu-fra
    github_push_repo: "ooni/test-lists"
    github_origin_repo: "citizenlab/test-lists"
    login_base_url: "https://test-lists.ooni.org/login"
    pg_uri: ""
    clickhouse_url: clickhouse://api:api@localhost/default
    base_url: "https://api.ooni.io"

- name: create Psiphon conffile
  tags: api
  copy:
    content: "{{ psiphon_config }}"
    dest: /etc/ooni/psiphon_config.json

- name: Write Tor targets conffile
  tags: api
  template:
    src: tor_targets.json
    dest: /etc/ooni/tor_targets.json

- name: configure api uploader using test bucket
  when: inventory_hostname == 'backend-hel.ooni.org'
  tags: api
  template:
    src: templates/api-uploader.conf
    dest: /etc/ooni/api-uploader.conf
  vars:
    # bucket_name and collector_id must match the API
    bucket_name: ooni-data-eu-fra-test
    collector_id: 2

- name: configure FSN api uploader using PROD bucket
  when: inventory_hostname == 'backend-fsn.ooni.org'
  tags: api
  template:
    src: templates/api-uploader.conf
    dest: /etc/ooni/api-uploader.conf
  vars:
    # bucket_name and collector_id must match the API
    bucket_name: ooni-data-eu-fra
    collector_id: 1

## Haproxy and nginx ##

- name: Overwrite API nginx test conf
  when: inventory_hostname == 'backend-hel.ooni.org'
  tags: api, webserv
  template:
    src: templates/nginx-api-test.conf
    dest: /etc/nginx/sites-available/ooni-api.conf
    mode: 0755
    owner: root
  vars:
    # Uses dehydrated
    certpath: /var/lib/dehydrated/certs/

- name: install haproxy if not present
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: webserv
  apt:
    cache_valid_time: 86400
    name: haproxy
    state: present

- name: Deploy haproxy conf
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: api, webserv
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0755
    owner: root
  vars:
    # Uses dehydrated
    certpath: /var/lib/dehydrated/certs/

- name: Delete old files
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: api, webserv
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/00-letsencrypt-http
    - /etc/nginx/sites-enabled/deb_ooni_org
    - /etc/nginx/sites-enabled/deb_ooni_org_http

- name: Deploy dehydrated conf
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: api, webserv
  template:
    src: templates/dehydrated.config
    dest: /etc/dehydrated/config
    mode: 0755
    owner: root

- name: Deploy dehydrated conf
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: api, webserv
  template:
    src: templates/dehydrated.config
    dest: /etc/dehydrated/config
    mode: 0755
    owner: root

- name: Deploy dehydrated haproxy hook
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: api, webserv
  template:
    src: templates/dehydrated_haproxy_hook.sh
    dest: /etc/dehydrated/haproxy_hook.sh
    mode: 0755
    owner: root

- name: Overwrite API nginx FSN conf
  when: inventory_hostname == 'backend-fsn.ooni.org'
  tags: api, webserv
  template:
    src: templates/nginx-api-fsn.conf
    dest: /etc/nginx/sites-available/ooni-api.conf
    mode: 0755
    owner: root
  vars:
    # Uses dehydrated
    certpath: /var/lib/dehydrated/certs/

- name: Deploy API gunicorn conf
  tags: api
  template:
    src: api.gunicorn.py
    dest: /etc/ooni/api.gunicorn.py
    owner: ooniapi
    group: ooniapi
    mode: 0640

- name: Create symlink for API nginx conf
  tags: api
  file:
    src=/etc/nginx/sites-available/ooni-api.conf
    dest=/etc/nginx/sites-enabled/ooni-api.conf
    state=link

- name: Configure deb.ooni.org forwarder on FSN host
  when: inventory_hostname in ('backend-fsn.ooni.org', )
  tags: deb_ooni_org
  # Uses dehydrated
  template:
    src: deb_ooni_org.nginx.conf
    dest: /etc/nginx/sites-enabled/deb_ooni_org

- name: Configure deb-ci.ooni.org forwarder on test host
  when: inventory_hostname == 'backend-hel.ooni.org'
  tags: deb_ooni_org
  blockinfile:
    path: /etc/nginx/sites-enabled/deb_ooni_org_http
    create: yes
    block: |
      # Managed by ansible, see roles/ooni-backend/tasks/main.yml
      server {
        listen 80;
        server_name deb-ci.ooni.org;
        location / {
          proxy_pass https://ooni-internal-deb.s3.eu-central-1.amazonaws.com/;
        }
      }

- name: create badges dir
  tags: api
  file:
    path: /var/www/package_badges/
    state: directory

- name: Safely reload Nginx
  # TODO remove restart after transition to haproxy
  tags: api, deb_ooni_org, webserv
  shell: nginx -t && systemctl reload nginx

- name: Restart Nginx
  tags: webserv
  shell: nginx -t && systemctl restart nginx

- name: Restart haproxy
  # reload is not enough
  when: inventory_hostname in ('backend-hel.ooni.org')
  tags: api, deb_ooni_org, webserv
  shell: systemctl restart haproxy

- name: allow incoming TCP connections to API
  tags: api
  blockinfile:
    path: /etc/ooni/nftables/tcp/443.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 443 counter accept comment "incoming HTTPS"

- name: allow incoming TCP connections to haproxy metrics
  tags: webserv
  template:
    src: 444.nft
    dest: /etc/ooni/nftables/tcp/444.nft

- name: reload nftables service
  tags: api, webserv
  shell: systemctl reload nftables.service

## Fastpath ##

- name: install fastpath if not present
  # do not update package if present
  when: inventory_hostname != 'backend-fsn.ooni.org'
  tags: fastpath
  apt:
    cache_valid_time: 86400
    name: fastpath
    state: present

- name: configure fastpath on test
  when: inventory_hostname == 'backend-hel.ooni.org'
  tags: fastpath
  template:
    src: fastpath.conf
    dest: /etc/ooni/fastpath.conf
    owner: fastpath
    group: fastpath
    mode: 0640
  vars:
    clickhouse_url: clickhouse://fastpath:fastpath@localhost/default

- name: configure fastpath on FSN
  when: inventory_hostname == 'backend-fsn.ooni.org'
  tags: fastpath
  template:
    src: fastpath.conf
    dest: /etc/ooni/fastpath.conf
    owner: fastpath
    group: fastpath
    mode: 0640
  vars:
    clickhouse_url: clickhouse://fastpath:fastpath@localhost/default

## Analysis daemon ##

- name: install analysis
  # do not update package if present
  when: inventory_hostname != 'backend-fsn.ooni.org'
  tags: analysis
  apt:
    cache_valid_time: 86400
    name: analysis=1.4~pr408-209
    force: True
    state: present

- name: configure analysis
  tags: analysis-conf
  template:
    src: analysis.conf
    dest: /etc/ooni/analysis.conf
      # Managed by ansible, see roles/ooni-backend/tasks/main.yml

- name: Run DB backup on backend-hel
  when: inventory_hostname == 'backend-hel.ooni.org'
  tags: dbbackup
  template:
    src: db-backup.conf
    dest: /etc/ooni/db-backup.conf
    mode: 0600
  vars:
    public_bucket_name: ooni-data-eu-fra-test

- name: Run DB backup on FSN
  when: inventory_hostname == 'backend-fsn.ooni.org'
  tags: dbbackup
  template:
    src: db-backup.conf
    dest: /etc/ooni/db-backup.conf
    mode: 0600
  vars:
    public_bucket_name: ooni-data-eu-fra
