package_update: true

packages:
  - nginx
  - unattended-upgrades

write_files:
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
        //"${distro_id} stable";
        "${distro_id} ${distro_codename}-security";
        "${distro_id} ${distro_codename}-updates";
      };

  - path: /etc/nginx/sites-available/default
    content: |
      %{ if length(wcth_addresses) > 0 }
      upstream wcths {
        %{ for address in wcth_addresses }
        server ${ address };
        %{ endfor }
      }
      server {
        server_name *.${ wcth_domain_suffix };
        listen 80;

        location / {
          proxy_pass http://wcths;
          proxy_http_version 1.1;
          proxy_set_header Host \$host;
        }
      }
      %{ endif }

      server {
        listen 80;

        server_name _;

        location / {
          proxy_pass ${backend_url};
          proxy_http_version 1.1;
          proxy_set_header Host \$host;
        }
        error_log /var/log/nginx/error.log;
      }

  - path: /etc/nginx/modules-enabled/stream.conf
    content: |
      stream {
        upstream clickhouse_backend {
          server ${clickhouse_url}:${clickhouse_port};
        }
      
        server {
          listen 9000;

          proxy_pass clickhouse_backend; 
        }

        error_log /var/log/nginx/error.log;
      }

runcmd:
  - service nginx restart
