apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
    - type: AWS/ECS
      regions:
        - eu-central-1
      period: 60
      length: 300
      searchTags:
        - key: Environment
          value: dev
      dimensionNameRequirements:
        - ClusterName
        - ServiceName
      metrics:
        - name: CPUUtilization
          statistics:
            - Average
        - name: MemoryUtilization
          statistics:
            - Average
