---
- name: "install jupyterhub"
  become: yes
  become_user: miniconda
  ansible.builtin.shell:
    cmd: "{{ miniconda_install_dir }}/bin/conda install -c conda-forge jupyterhub"

- name: "install jupyterlab and notebook"
  become: yes
  become_user: miniconda
  ansible.builtin.shell:
    cmd: "{{ miniconda_install_dir }}/bin/conda install jupyterlab notebook"

- name: Write jupyterhub config
  ansible.builtin.template:
    src: jupyterhub_config.py.j2
    dest: "{{ jupyterhub_config_dir }}/config.py"
    owner: root
    group: {{ admin_group }}
    mode: "0640"
  notify:
    - Restart jupyterhub

- name: Write jupyterhub service
  ansible.builtin.template:
    src: jupyterhub.service.j2
    dest: "/etc/systemd/system/jupyterhub.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart jupyterhub

- name: Ensure the JupyterHub service is started with daemon-reload
  become: true
  tags:
    - config
  ansible.builtin.systemd:
    name: jupyterhub
    state: started
    enabled: true
    daemon_reload: true
