---
- include_tasks: jupyterhub.yml

- include_role:
    name: geerlingguy.certbot
  vars:
    certbot_admin_email: admin@ooni.org
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - "{{ inventory_name }}"
