- name: create pipeline configuration
  ansible.builtin.file:
    path: "/etc/ooni/pipeline/"
    state: directory
    owner: oonipipeline
  tags:
    - oonipipeline

- name: create pipeline configuration
  ansible.builtin.file:
    path: "{{ oonipipeline_runtime_dir }}"
    state: directory
    owner: oonipipeline
  tags:
    - oonipipeline

- name: copy configuration files
  ansible.builtin.copy:
    content: "{{ lookup('amazon.aws.aws_secret', 'oonidevops/{{ item }}', profile='oonidevops_user_prod') }}"
    dest: /etc/ooni/pipeline/{{item}}
    owner: oonipipeline
    mode: "0600"
  loop:
    - ooni-pipeline.uuhzf.crt
    - ooni-pipeline.uuhzf.key
  tags:
    - oonipipeline

- name: write oonipipeline configuration
  ansible.builtin.template:
    src: oonipipeline-config.toml.j2
    dest: /etc/ooni/pipeline/oonipipeline-config.toml
    owner: oonipipeline
    mode: "0600"
  tags:
    - oonipipeline

- name: Write oonipipeline service
  ansible.builtin.template:
    src: oonipipeline-worker.service.j2
    dest: "/etc/systemd/system/oonipipeline-worker.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart oonipipeline-worker
  tags:
    - oonipipeline

- name: Ensure the OONI pipeline worker service is started with daemon-reload
  ansible.builtin.systemd:
    name: oonipipeline-worker
    state: started
    enabled: true
    daemon_reload: true
  tags:
    - oonipipeline
