---
- name: Configure ClickHouse servers using a template
  hosts: clickhouse_servers
  user: admin
  become: yes
  vars:
    clickhouse_reader_password: "{{ lookup('env', 'CLICKHOUSE_READER_PASSWORD') }}"
  tasks:
    - name: install clickhouse requirements
      tags: clickhouse
      apt:
        cache_valid_time: 86400
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - dirmngr

    - name: Create a temporary directory for GPG
      ansible.builtin.tempfile:
        state: directory
      register: gnupg_temp_dir

    - name: Import ClickHouse GPG key
      ansible.builtin.command:
        cmd: "gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754"
        chdir: "{{ gnupg_temp_dir.path }}"
        creates: "/usr/share/keyrings/clickhouse-keyring.gpg"
      environment:
        GNUPGHOME: "{{ gnupg_temp_dir.path }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ gnupg_temp_dir.path }}"
        state: absent

    - name: Ensure the keyring is readable
      ansible.builtin.file:
        path: /usr/share/keyrings/clickhouse-keyring.gpg
        mode: a+r

    - name: Add ClickHouse repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main"
        state: present
        filename: clickhouse

    - name: Update the package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ClickHouse server and client
      ansible.builtin.apt:
        name:
          - clickhouse-server={{ clickhouse_pkg_ver }}
          - clickhouse-client={{ clickhouse_pkg_ver }}
          - clickhouse-common-static={{ clickhouse_pkg_ver }}
        state: present
      vars:
        clickhouse_pkg_ver: 24.1.*

    - name: Ensure ClickHouse service is started and enabled
      ansible.builtin.systemd:
        name: clickhouse-server
        state: started
        enabled: yes

    - name: Configure ClickHouse users from template
      template:
        src: templates/ooni_users.xml
        dest: /etc/clickhouse-server/users.d/ooni_users.xml
        owner: clickhouse
        group: clickhouse
        mode: '0640'
      notify:
        - restart clickhouse-server

  handlers:
    - name: restart clickhouse-server
      service:
        name: clickhouse-server
        state: restarted