---
- name: Create statsd_exporter group
  ansible.builtin.group:
    name: statsd_exporter
    state: present
  become: true

- name: Create statsd_exporter user
  ansible.builtin.user:
    name: statsd_exporter
    group: statsd_exporter
    shell: /sbin/nologin
    system: true
    createhome: false
  become: true

- name: Check current statsd_exporter version
  ansible.builtin.command: "{{ statsd_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: exporter_installed

# We can't install it with apt-get, use the binary from github
- name: Download and unarchive statsd_exporter
  ansible.builtin.unarchive:
    src: "{{ statsd_exporter_download_url }}"
    dest: /tmp/
    remote_src: true
    mode: "0755"
  when: exporter_installed.rc != 0 # return code (rc) is != 0 when not installed
  register: exporter_downloaded
  become: true

- name: Move statsd_exporter binary into place
  ansible.builtin.copy:
    src: "/tmp/{{ statsd_exporter_filename }}/statsd_exporter"
    dest: "{{ statsd_exporter_bin_path }}"
    mode: "0755"
    remote_src: true
  when: exporter_installed.rc != 0
  notify: restart statsd_exporter
  become: true

- name: Create statsd_exporter systemd unit
  ansible.builtin.template:
    src: statsd_exporter.service
    dest: /etc/systemd/system/statsd_exporter.service
    mode: "0644"
  register: statsd_exporter_service
  become: true
  notify: restart statsd_exporter

- name: Reload systemd daemon if statsd_exporter unit file changed
  ansible.builtin.systemd:
    daemon_reload: true
  when: statsd_exporter_service is changed
  become: true

- name: Ensure statsd_exporter is running and enabled
  ansible.builtin.service:
    name: statsd_exporter
    state: started
    enabled: true
  become: true
