- name: Test nginx config
  command: /usr/sbin/nginx -t -c /etc/nginx/nginx.conf
  listen:
    - Restart nginx-prometheus
    - Reload nginx-prometheus

- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: Reload nftables
  tags: nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded
