stream {
    upstream clickhouse_default {
        server {{ clickhouse_url }}:{{ clickhouse_port }};
    }

    upstream clickhouse_1 {
        server {{ clickhouse_url_1 }}:{{ clickhouse_port }};
    }

    upstream clickhouse_2 {
        server {{ clickhouse_url_2 }}:{{ clickhouse_port }};
    }

    # Port-based routing on clickhouseproxy.<env>.ooni.io:
    #   9000 -> clickhouse_url (default)
    #   9001 -> clickhouse_url_1
    #   9002 -> clickhouse_url_2
    server {
        listen 9000;
        proxy_pass clickhouse_default;
    }

    server {
        listen 9001;
        proxy_pass clickhouse_1;
    }

    server {
        listen 9002;
        proxy_pass clickhouse_2;
    }

    error_log /var/log/nginx/error.log;
}
