---
- name: Install nftables
  ansible.builtin.apt:
    cache_valid_time: 86400
    name: nftables
  tags:
    - nftables

- name: create config dir
  ansible.builtin.file:
    path: /etc/ooni/nftables/tcp
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - nftables

- name: allow SSH
  ansible.builtin.blockinfile:
    path: /etc/ooni/nftables/tcp/22.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 22 counter accept comment "Incoming SSH"
  tags:
    - nftables

- name: Overwrite nftables.conf
  ansible.builtin.template:
    src: templates/nftables.conf
    dest: /etc/nftables.conf
    mode: 0755
    owner: root
  notify:
    - Reload nftables
  tags:
    - nftables

- name: enable nftables service
  ansible.builtin.systemd_service:
    name: nftables
    enabled: yes
    state: started
  tags:
    - nftables
