---
- name: install nginx
  include_role:
    name: nginxinc.nginx

- name: remove `default` vhost
  file: path={{item}} state=absent
  notify: reload nginx
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default

- name: set nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0444
  notify: reload nginx
...
