---
# For prometheus scrape requests
- name: Flush all handlers
  meta: flush_handlers

- name: Allow Nomad HTTP traffic
  become: true
  tags:
    - nomad-ports
    - nftables
  blockinfile:
    path: /etc/ooni/nftables/tcp/4646.nft
    create: true
    block: |
      add rule inet filter input tcp dport 4646 counter accept comment "nomad http api and web ui"
  notify:
   - Reload nftables

- name: Allow Nomad RPC traffic
  become: true
  tags:
    - nomad-ports
    - nftables
  blockinfile:
    path: /etc/ooni/nftables/tcp/4647.nft
    create: true
    block: |
      add rule inet filter input tcp dport 4647 counter accept comment "nomad rpc"
  notify:
   - Reload nftables

- name: Install Docker prerequisites
  tags: docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gpg
      - coreutils
    state: present

- name: Create keyring directory
  tags: [docker, nomad]
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  tags: docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker.asc
    mode: '0644'

- name: Dearmor Docker GPG key
  tags: docker
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker.asc
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker apt repository
  tags: docker
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Install Docker
  tags: docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Ensure Docker service is enabled and started
  tags: docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Download HashiCorp GPG key
  tags: nomad
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.asc
    mode: '0644'

- name: Dearmor HashiCorp GPG key
  tags: nomad
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.asc
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp apt repository
  tags: nomad
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present

- name: Install Nomad
  tags: nomad
  ansible.builtin.apt:
    name: nomad
    state: present
    update_cache: yes

- name: Create Nomad configuration directory
  tags: nomad
  ansible.builtin.file:
    path: /etc/nomad.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Setup Nomad in dev mod
  tags: nomad
  ansible.builtin.copy:
    dest: /etc/nomad.d/nomad.hcl # Main config file
    content: |
      bind_addr = "0.0.0.0"
      data_dir = "/opt/nomad/data"

      server {
        enabled          = true
        bootstrap_expect = 1
      }

      client {
        enabled = true
        servers = ["127.0.0.1"]
      }

      acl {
        enabled = true
      }
    mode: '0644'
    owner: root
    group: root
  notify: restart nomad

- name: Ensure Nomad service is enabled and started
  tags: nomad
  ansible.builtin.service:
    name: nomad
    state: started
    enabled: yes
