---
- name: Include monitoring playbook
  ansible.builtin.import_playbook: deploy-monitoring.yml

- name: Include ooni-backend playbook
  ansible.builtin.import_playbook: deploy-ooni-backend.yml

- name: Include ooni-clickhouse-proxy playbook
  ansible.builtin.import_playbook: deploy-clickhouse-proxy.yml

- name: Include clickhouse playbook
  ansible.builtin.import_playbook: deploy-clickhouse.yml

- name: Deploy oonidata worker nodes
  hosts:
    - data1.htz-fsn.prod.ooni.nu
  become: true
  tags:
    - oonidata_worker
  roles:
    - oonidata
  vars:
    enable_jupyterhub: false
    enable_oonipipeline_worker: true
    clickhouse_url: "clickhouse://write:{{ lookup('amazon.aws.aws_ssm', '/oonidevops/secrets/clickhouse_write_password', profile='oonidevops_user_prod') | hash('sha256') }}@clickhouse1.prod.ooni.io/ooni"
