---
- name: Deploy clickhouse proxy
  hosts:
    - clickhouseproxy.dev.ooni.io
  become: true
  roles:
    - role: bootstrap
    - role: dehydrated
      vars: 
        ssl_domains: 
          - clickhouseproxy.dev.ooni.io
    - role: nginx
      tags: nginx
    - role: clickhouse_proxy
      vars: 
        clickhouse_url: "clickhouse3.prod.ooni.io"
        clickhouse_port: 9000
        clickhouse_proxy_public_fqdn: "clickhouseproxy.dev.ooni.io"
    - role: dehydrated
      vars:
        ssl_domains: "clickhouseproxy.dev.ooni.io"
        tls_cert_dir: /var/lib/dehydrated/certs
    - role: prometheus_node_exporter
      vars:
        node_exporter_port: 9100
        node_exporter_host: "0.0.0.0"
        prometheus_nginx_proxy_config: 
          - location: /metrics/node_exporter
            proxy_pass: http://127.0.0.1:9100/metrics
