---
- hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - ssh_users
    - ansible_controller
    - prometheus_node_exporter
  vars:
    node_exporter_port: 9100
    node_exporter_host: "0.0.0.0"
    prometheus_nginx_proxy_config: 
      - location: /metrics/node_exporter
        proxy_pass: http://127.0.0.1:9100/metrics
