---
- name: Deploy oonidata clickhouse hosts
  hosts:
    - notebook.ooni.org
    - data1.htz-fsn.prod.ooni.nu
    - data2.htz-fsn.prod.ooni.nu
    - data3.htz-fsn.prod.ooni.nu
  become: true
  roles:
    - role: prometheus_node_exporter
      tags: [node_exporter]
    - role: oonidata_clickhouse
      tags: [clickhouse]
