---
- name: Deploy the Web Connectivity test helper
  hosts:
    - wc.th.dev.ooni.io
    - wcth0.fra1.prod.ooni.io
    - wcth1.fra1.prod.ooni.io
    - wcth2.fra1.prod.ooni.io
  become: true
  vars:
    ssl_domains:
      - "{{ inventory_hostname }}"
    nginx_install_method: official_repo
  roles:
    - role: bootstrap
    - role: nginx
    - role: dehydrated
    - role: prometheus_node_exporter
      vars:
        use_https: true
        https_port: 9001
    - role: oohelperd
