---
- name: Include monitoring playbook
  ansible.builtin.import_playbook: deploy-monitoring.yml

- name: Include ooni-backend playbook
  ansible.builtin.import_playbook: deploy-ooni-backend.yml

- name: Include clickhouse playbook
  ansible.builtin.import_playbook: deploy-clickhouse.yml

- name: Include airflow playbook
  ansible.builtin.import_playbook: deploy-airflow.yml
