---
- name: Deploy ooni backend services
  hosts: backend-hel.ooni.org
  become: true
  roles:
    # - role: bootstrap
      # vars:
        # admin_group_name: adm
    # - role: base-backend
    # - role: nftables
    # - role: nginx
      # tags: nginx
      # vars:
        # nginx_user: "www-data"
    # - role: dehydrated
      # tags: dehydrated
      # expand: yes
      # vars: 
        # ssl_domains:
          # # with dehydrated the first entry is the cert FQDN
          # # and the other ones are alternative names
          # - "backend-hel.ooni.org"
    - role: ooni-backend
      vars: 
        ssl_domain: backend-hel.ooni.org
        collector_id: 2
        clickhouse_url: "clickhouse://write:{{ lookup('amazon.aws.aws_ssm', '/oonidevops/secrets/clickhouse_write_password', profile='oonidevops_user_prod') }}@clickhouse3.prod.ooni.io/oonitest"
        bucket_name: ooni-data-eu-fra-test
        public_bucket_name: ooni-data-eu-fra-test
        collectors: 
          - "backend-hel.ooni.org"
        fastpath_version: 0.86~pr831-395
        analysis_version: 1.12~pr836-412
        deb_bucket_name: ooni-internal-deb
        deb_server_name: deb-cli.ooni.org
