---
## - name: Deploy clickhouse proxy
  ## hosts:
    ## - clickhouseproxy.dev.ooni.io
  ## roles:
    ## - role: bootstrap
    ## - role: nginx
      ## tags: nginx
    ## - role: clickhouse_proxy
      ## vars: 
        ## clickhouse_url: "" # fetch from AWS secrets
