---
- name: ClickHouse servers
  hosts: clickhouse_servers
  user: admin
  become: true
  vars:
    clickhouse_reader_password: "{{ lookup('env', 'CLICKHOUSE_READER_PASSWORD') }}"
  roles:
    - clickhouse
  handlers:
    - name: Restart clickhouse-server
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

- name: Update monitoring config
  hosts: monitoring.ooni.org
  become: true
  roles:
    - prometheus
    - prometheus_blackbox_exporter
    - prometheus_alertmanager

- name: Deploy data.ooni.org host
  hosts: data.ooni.org
  become: true
  roles:
    - clickhouse
    - ssh_users
    - jupyterhub
