---
- name: Include bootstrap playbook
  ansible.builtin.import_playbook: deploy-bootstrap.yml

- name: Include tier0 playbook
  ansible.builtin.import_playbook: deploy-tier0.yml

- name: Include tier2 playbook
  ansible.builtin.import_playbook: deploy-tier2.yml
