---
- name: Ensure all hosts are bootstrapped correctly
  hosts: all
  become: yes
  roles:
    - bootstrap
  tags:
    - bootstrap

- name: Update monitoring config
  hosts: monitoring.ooni.org
  become: true
  roles:
    - prometheus
    - prometheus_blackbox_exporter
    - prometheus_alertmanager

- name: Setup OpenVPN server
  hosts: openvpn-server1.ooni.io
  become: true
  remote_user: root
  roles:
    - ssh_users

- name: Deploy oonidata clickhouse hosts (ssd backed)
  hosts:
    - data1.htz-fsn.prod.ooni.nu
    - data2.htz-fsn.prod.ooni.nu
  become: true
  roles:
    - oonidata_clickhouse

- name: Deploy oonidata clickhouse hosts (hdd backed)
  hosts:
    - data3.htz-fsn.prod.ooni.nu
  become: true
  roles:
    - oonidata_clickhouse
  vars:
    clickhouse_data_directory: /data/clickhouse

- name: Deploy notebook host
  hosts: notebook.ooni.org
  become: true
  vars:
    enable_oonipipeline_worker: false
  roles:
    - oonidata

# commented out due to the fact it requires manual config of ~/.ssh/config
#- name: Setup codesign box
#  hosts: codesign-box
#  become: true
#  remote_user: ubuntu
#  roles:
#    - codesign_box
