---
- name: ClickHouse servers
  hosts: clickhouse_servers
  user: admin
  become: yes
  vars:
    clickhouse_reader_password: "{{ lookup('env', 'CLICKHOUSE_READER_PASSWORD') }}"
  roles:
    - clickhouse
  handlers:
    - name: restart clickhouse-server
      service:
        name: clickhouse-server
        state: restarted

- name: Update monitoring config
  hosts: monitoring.ooni.org
  become: yes
  roles:
    - prometheus
    - prometheus_blackbox_exporter
    - prometheus_alertmanager

- name: Setup OpenVPN server
  hosts: openvpn-server1.prod.ooni.io
  become: yes
  vars:
    extra_users:
      - ain
    extra_ssh_users:
      ain:
        login: ain
        comment: Ain
        keys: ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH6Js4xtJq7AoYA8mFraQg8vYgKz/glil9AaPq4lDwtg ain@intertubes"]
    ssh_users: "{{ ssh_users | ansible.builtin.combine(extra_ssh_users) }}"
    admin_usernames: "{{ admin_usernames + extra_users }}"
  roles:
    - ssh_users
