---
- name: Check if Miniconda is installed
  ansible.builtin.stat:
    path: "{{ miniconda_install_dir }}/bin/conda"
  register: miniconda_bin

- include_tasks: install.yml
  when: not miniconda_bin.stat.exists

- name: "install conda packages"
  ansible.builtin.shell:
    cmd: "{{ miniconda_install_dir }}/bin/conda install -y {{ item }}"
  loop:
    - pandas
    - numpy
    - altair
